<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Eco.ReferenceAssemblies" />
	  <PackageReference Include="ConcurrentHashSet" />
	  <PackageReference Include="Newtonsoft.Json" />
	  <PackageReference Include="StrangeLoopGames.PropertyChanged.Fody"  PrivateAssets="All" />
  </ItemGroup>

</Project>
